package io.complyance.sdk;

public enum LogicalDocType {
    // Base types
    INVOICE,
    CREDIT_NOTE,
    DEBIT_NOTE,
    RECEIPT,
    // B2B Tax Invoice types
    TAX_INVOICE,
    TAX_INVOICE_CREDIT_NOTE,
    TAX_INVOICE_DEBIT_NOTE,
    TAX_INVOICE_PREPAYMENT,
    TAX_INVOICE_PREPAYMENT_ADJUSTED,
    TAX_INVOICE_EXPORT_INVOICE,
    TAX_INVOICE_EXPORT_CREDIT_NOTE,
    TAX_INVOICE_EXPORT_DEBIT_NOTE,
    TAX_INVOICE_THIRD_PARTY_INVOICE,
    TAX_INVOICE_SELF_BILLED_INVOICE,
    TAX_INVOICE_NOMINAL_SUPPLY_INVOICE,
    TAX_INVOICE_SUMMARY_INVOICE,
 

    
    // B2C Simplified Tax Invoice types
    SIMPLIFIED_TAX_INVOICE,
    SIMPLIFIED_TAX_INVOICE_CREDIT_NOTE,
    SIMPLIFIED_TAX_INVOICE_DEBIT_NOTE,
    SIMPLIFIED_TAX_INVOICE_PREPAYMENT,
    SIMPLIFIED_TAX_INVOICE_PREPAYMENT_ADJUSTED,
    SIMPLIFIED_TAX_INVOICE_EXPORT_INVOICE,
    SIMPLIFIED_TAX_INVOICE_EXPORT_CREDIT_NOTE,
    SIMPLIFIED_TAX_INVOICE_EXPORT_DEBIT_NOTE,
    SIMPLIFIED_TAX_INVOICE_THIRD_PARTY_INVOICE,
    SIMPLIFIED_TAX_INVOICE_SELF_BILLED_INVOICE,
    SIMPLIFIED_TAX_INVOICE_NOMINAL_SUPPLY_INVOICE,
    SIMPLIFIED_TAX_INVOICE_SUMMARY_INVOICE,
    
    
    // Country-specific logical types
    EXPORT_INVOICE,
    EXPORT_CREDIT_NOTE,
    EXPORT_DEBIT_NOTE,
    EXPORT_THIRD_PARTY_INVOICE,
    THIRD_PARTY_INVOICE,
    SELF_BILLED_INVOICE,
    NOMINAL_SUPPLY_INVOICE,
    SUMMARY_INVOICE,
    
    // Germany (DE) specific logical document types
    // Partial invoices
    TAX_INVOICE_PARTIAL,
    TAX_INVOICE_PARTIAL_SELF_BILLED,
    
    // Construction invoices
    TAX_INVOICE_PARTIAL_CONSTRUCTION,
    TAX_INVOICE_PARTIAL_FINAL_CONSTRUCTION,
    TAX_INVOICE_FINAL_CONSTRUCTION,
    
    // Export combinations
    TAX_INVOICE_EXPORT_SELF_BILLED,
    TAX_INVOICE_EXPORT_PARTIAL,
    
    // B2G (Business-to-Government) documents
    TAX_INVOICE_B2G,
    CREDIT_NOTE_B2G,
    DEBIT_NOTE_B2G,
    TAX_INVOICE_B2G_SELF_BILLED,
    TAX_INVOICE_B2G_PARTIAL,
    TAX_INVOICE_B2G_PARTIAL_CONSTRUCTION,
    TAX_INVOICE_B2G_PARTIAL_FINAL_CONSTRUCTION,
    TAX_INVOICE_B2G_FINAL_CONSTRUCTION
}
